<?php

/**
 * @file
 * Alert administrators before starting the import process.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_upgrade_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.migrate_upgrade':
      $output = '<p>' . t('The Drupal Upgrade UI module provides a one-click upgrade from an earlier version of Drupal. For more details, see <a href="!migrate">upgrading from previous versions</a>.', ['!migrate' => 'https://www.drupal.org/upgrade']) . '</p>';
      return $output;
    case 'migrate_upgrade.upgrade':
      $output = '<p>' . t('This form is used for upgrading configuration and content from a previous version of your Drupal site. Make sure you have backups of your destination site before submitting this form. Also, ensure that the source database and files are accessible to the destination site. For more details, see <a href="!migrate">upgrading from previous versions</a>.', ['!migrate' => 'https://www.drupal.org/upgrade']) . '</p>';
      return $output;
  }
}
